apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.image.secret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env.global }}
            - name: {{ $key  }}
              value: {{ $val | quote }}
            {{- end }}

            {{- if .Values.env.local.MONGO_ADDR }}
            - name: MONGO_ADDR
              value: "{{ .Values.env.local.MONGO_ADDR }}"
            {{- else }}
            - name: MONGO_ADDR
              value: "{{ .Release.Name }}-mongodb:27017"
            {{- end }}

            {{- if .Values.env.local.KUBE_API_ADDR }}
            - name: KUBE_API_ADDR
              value: "{{ .Values.env.local.KUBE_API_ADDR }}"
            {{- else }}
            - name: KUBE_API_ADDR
              value: "http://{{ .Release.Name }}-kube:1214"
            {{- end }}

            {{- if .Values.env.local.PERMISSIONS_ADDR }}
            - name: PERMISSIONS_ADDR
              value: "{{ .Values.env.local.PERMISSIONS_ADDR }}"
            {{- else }}
            - name: PERMISSIONS_ADDR
              value: "http://{{ .Release.Name }}-permissions:4242"
            {{- end }}

            {{- if .Values.env.local.MONGO_PASSWORD }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: mongodb-password
            {{- else if .Values.tags.platformdb }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb
                  key: mongodb-password
            {{- end }}
