stages:
  - test
  - build
  - deploy

.create_tag: &create_tag
  before_script:
    - export DATE=$(date +"%Y-%m-%d")
    - export TAG="${DATE}-${CI_COMMIT_SHA:0:8}"

build-and-push-develop:
  <<: *create_tag
  services:
    - docker:dind
  image: docker:latest
  stage: build
  tags:
    - build
  script:
    - docker login ${DOCKER_REGISTRY} -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - docker build --pull -t ${DOCKER_REGISTRY_IMAGE}:${TAG} .
    - docker push "${DOCKER_REGISTRY_IMAGE}:${TAG}"
  only:
    - develop

deploy-to-kubernetes-develop:
  <<: *create_tag
  image: mastanggt/kubectl:latest
  stage: deploy
  tags:
    - deploy
  script:
    - export IMAGE="$DOCKER_REGISTRY_IMAGE:${TAG}"
    - echo $SANDBOX_KUBE_CONFIG | base64 -d > admin.conf
    - cat deploy-template.yaml | envsubst > deploy.yaml
    - kubectl --kubeconfig=admin.conf replace -f deploy.yaml
  only:
    - develop


docker-build-test:
  <<: *create_tag
  services:
    - docker:dind
  image: docker:latest
  stage: test
  tags:
    - test
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build --cache-from=${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${TAG} .
  except:
    - develop

migrations-test:
  <<: *create_tag
  variables:
    POSTGRES_USER: migtest
    POSTGRES_PASSWORD: migtest
    POSTGRES_DB: migtest
    MIGRATIONS_DIR: ./migrations
    DOCKER_HOST: tcp://docker:2375
  services:
    - postgres:latest
  image: golang:1.9-alpine
  stage: test
  script:
    - apk add --no-cache git
    - go get -v --tags="postgres" github.com/mattes/migrate/cli
    - export DB_URL="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_PORT_5432_TCP_ADDR/$POSTGRES_DB?sslmode=disable"
    - cli -verbose -path=$MIGRATIONS_DIR -database=$DB_URL up
    - cli -verbose -path=$MIGRATIONS_DIR -database=$DB_URL down
