
[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/utils"

[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "3.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"
