[prune]
    non-go = true
    go-tests = true
    unused-packages = true

[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/utils"

[[constraint]]
  version = "1.2.0"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  revision = "05cef0741ade10ca668982355b3f3f0bcf0ff0a8"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  revision = "19c8e9ad00952ce0c64489b60e8df88bb16dd514"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattes/migrate"
  version = "3.0.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "git.containerum.net/ch/kube-client"
  version = "~0.2.0"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/kube-api"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.12.0"

[[constraint]]
  name = "github.com/go-playground/locales"
  version = "0.11.2"

[[constraint]]
  branch = "master"
  name = "git.containerum.net/ch/json-types"

[[constraint]]
  version = "kubernetes-1.9.3"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/auth"