BEGIN TRANSACTION;
DROP TABLE IF EXISTS namespaces;
DROP TABLE IF EXISTS accesses;
DROP TABLE IF EXISTS log;
DROP TYPE IF EXISTS ResourceKind;
DROP TYPE IF EXISTS AccessLevel;
COMMIT TRANSACTION;

DROP EXTENSION IF EXISTS "uuid-ossp";