BEGIN TRANSACTION;
ALTER TABLE namespaces
  AlTER COLUMN create_time SET DATA TYPE TIMESTAMP,
  ALTER COLUMN delete_time SET DATA TYPE TIMESTAMP;
ALTER TABLE accesses
  ALTER COLUMN create_time SET DATA TYPE TIMESTAMP,
  ALTER COLUMN access_level_change_time SET DATA TYPE TIMESTAMP;
ALTER TABLE volumes
  ALTER COLUMN create_time SET DATA TYPE TIMESTAMP,
  ALTER COLUMN delete_time SET DATA TYPE TIMESTAMP;
ALTER TABLE deployments
  ALTER COLUMN create_time SET DATA TYPE TIMESTAMP,
  ALTER COLUMN delete_time SET DATA TYPE TIMESTAMP;
ALTER TABLE log
  ALTER COLUMN t SET DATA TYPE TIMESTAMP;
COMMIT TRANSACTION;