tags:
  db: true
  platformdb: false

replicaCount: 1

image:
  repository: containerum/resource
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 1213
  targetPort: 1213
  externalIP:

env:
  global:
    DEBUG: "true"
    TEXTLOG: "true"
    MONGO_LOGIN: "resource"
    MONGO_DB: "resource"
    MIN_SERVICE_PORT: 30000
    MAX_SERVICE_PORT: 32767
  local:
    MONGO_ADDR: "mongo-mongodb.mongo.svc.cluster.local:27017"
    KUBE_API_ADDR: "http://kube:1214"
    MONGO_PASSWORD:
    PERMISSIONS_ADDR: "http://permissions:4242"

mongodb:
  persistence:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  mongodbUsername: mongo
  mongodbDatabase: resource
  # mongodbPassword: password
